#!/usr/bin/env bash
set -e

# CLEAN_ALL, BUILD_ALL, and BUILD_LIST are set in the docker/env file.
main() {
  cd /mnt/docker
  python3 -u ./init.py 2>&1
}

main "${@}"
# This keeps the docker image from exiting.
exec /bin/bash
exit 0
